---
- name: Controller Playbook
  hosts: controller-nodes
  become: yes
  roles:
    - common
    - controller
    - keystone
    - glance
    - cont-nova
    - cont-neutron
    - horizon
    #- cont-cinder
