---
- name: Controller Playbook
  hosts: controller-1
  become: yes
  roles:
    - common
    - controller
    - keystone
    #- glance
    #- cont-nova
    #- cont-neutron
    #- horizon
    #- cont-cinder
