---
- name: Test Playbook
  hosts: controller-1
  become: yes
  vars:
    mgt_ip: "{{hostvars['controller-1'].ansible_host}}"
    KEYSTONE_DBPASS: keystonedbpass

  tasks:
#  - name: edit etcd
#    template:
#      src: roles/controller/templates/etcd.template
#      dest: /etc/etcd/etcd.conf.yml
  - name: edit keystone.conf
    shell: echo \
      "hello world"
