---
- name: Test Playbook
  hosts: compute-1
  become: yes
  vars:
    mgt_ip: "{{hostvars['controller-1'].ansible_host}}"
    mysql_root_password: rootdbpass
    NOVA_DBPASS: novadbpass
    ADMIN:
      env:
        OS_PROJECT_DOMAIN_NAME: Default
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: adminpass
        OS_AUTH_URL: http://controller:35357/v3
        OS_IDENTITY_API_VERSION: 3
        OS_IMAGE_API_VERSION: 2
    num: 0
  tasks:
#    - shell: "echo {{ item }}"
#      loop:
#        - "one"
#        - "two"
#      register: echo
#    - debug:
#        msg: "{{ item.stdout }}"
#      loop: "{{ echo.results }}"
#    - name: edit /etc/network/interfaces
#      debug:
#        msg: "{{ansible_host}}"
#    - name: show other interface
#      debug:
#        msg: "{{ansible_interfaces[2]}}"
#  - name: Add IP address of all hosts to all hosts
#    lineinfile:
#      dest: /etc/hosts
#      line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
#      state: present
#    with_items: "{{ groups.all }}"
    - name: Reboot node for the changes to take effect
      shell: /sbin/shutdown -r +1 "Triggered by Ansible"
      async: 0
      poll: 0
      #ignore_errors: true

    - name: Wait for node to UP
      wait_for_connection:
        sleep: 120
        delay: 180
        timeout: 300
