---
# vars file for comp-neutron
def_interface: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['interface']}}"
def_address: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
def_netmask: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['netmask']}}"
def_gateway: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['gateway']}}"
#edit this depends on the 2nd interface name
extra_interface: "{{ansible_interfaces[2]}}"
RABBIT_PASS: rabbitmqpass
NEUTRON_PASS: neutronpass
METADATA_SECRET: mdsecret
...
