---
# tasks file for keystone
- name: Use the database access client to connect to the database server as the root user
- name: Create keystone DB
- name: Grant access to keystone DB
- name: Install keystone components
- name: Edit /etc/keystone/keystone.conf
- name: Populate the Identity service database
- name: Initialize Fernet key repositories
- name: Bootstrap the Identity service
- name: Edit the /etc/apache2/apache2.conf
- name: Restart the Apache service
- name: Copy environment scripts
- name: Run admin-openrc
- name: Create "Service Project"
- name: Create "Demo Project"
- name: Create demo user
- name: Create user role
- name: Add the user role to the demo project and user
...
