---
# tasks file for horizon
- name: Install horizon package
  apt:
    name: openstack-dashboard
    state: present
    allow_unauthenticated: yes

- name: Edit the /etc/openstack-dashboard/local_settings.py
  template:
    src: local_settings.py.template
    dest: /etc/openstack-dashboard/local_settings.py

- name: Edit /etc/apache2/conf-available/openstack-dashboard.conf
  lineinfile:
    path: /etc/apache2/conf-available/openstack-dashboard.conf
    regexp: '^WSGIApplicationGroup'
    line: 'WSGIApplicationGroup %{GLOBAL}'

- name: Reload the web server configuration
  service:
    name: apache2
    state: reloaded
  changed_when: false
...
